services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    ports:
      - 32400:32400        # Plex Web / TV App
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Kampala
      - ADVERTISE_IP=http://192.168.1.2:32400/
    volumes:
      - plex_config:/config
      - /host_mnt/c/Users/expedicto.walugembe/Videos:/data/videos
      - /host_mnt/c/Users/expedicto.walugembe/Music:/data/music
      - /host_mnt/c/Users/expedicto.walugembe/AppData/Local/Temp:/transcode
    restart: unless-stopped

volumes:
  plex_config:
